services:
  proxy:
    image: traefik:latest
    restart: unless-stopped
    command:
      - --entrypoints.web.address=:3000
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --api

    ports:
    - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy.service=api@internal

  core-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: interv-dev
      POSTGRES_PASSWORD: interv-dev
      POSTGRES_DB: interv-dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z.fips
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=interv
      - MINIO_ROOT_PASSWORD=intervinterv
    volumes:
      - minio_data:/data
    command:
      - server
      - /data
      - --console-address
      - ":9001"

  frontend:
    image: oupsn/interv-clientside:latest
    restart: always
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)

  backend:
    image: oupsn/interv-core:latest
    restart: always
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_ORIGINS: "http://localhost:3000"
      SERVER_PORT: 5000
      DB_AUTOMIGRATE: true
      DB_HEADLESS: false
      DB_HOST: "core-db"
      DB_NAME: "interv-dev"
      DB_USERNAME: "interv-dev"
      DB_PASSWORD: "interv-dev"
      DB_PORT: 5432
      JWT_SECRET: "korHaiProjectNeePanPaiDaiDeeee"
      ENV: "sit"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: interv
      MINIO_SECRET_KEY: intervinterv
      COMPILER_ENDPOINT: "http://47.243.33.180:2358/"
      PYTHON_LINTER_ENDPOINT: "http://47.243.33.180:8080/api/analyze"
      JAVA_LINTER_ENDPOINT: "http://47.243.33.180:8081/api/analyze"
      C_LINTER_ENDPOINT: "http://47.243.33.180:8082/api/analyze"
      REDIS_URL: "redis://redis:6379"
      TEMP_DIR: "/tmp/coding-interview-chunks"
    depends_on:
      - core-db
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)

volumes:
  postgres_data:
  redis_data:
  minio_data: